namespace HashTagSearcher.Controllers
{
    public class WordLists
    {
        public static readonly string[] BadWords =
        {
            "infest",
            "Bad".ToLower(),
            "Atrocious".ToLower(),
            "Awful".ToLower(),
            "Cheap".ToLower(),
            "Crummy".ToLower(),
            "Dreadful".ToLower(),
            "Lousy".ToLower(),
            "Poor".ToLower(),
            "Rough".ToLower(),
            "Sad".ToLower(),
            "Unacceptable".ToLower(),
            "Blah".ToLower(),
            "Bummer".ToLower(),
            "Diddly".ToLower(),
            "Downer".ToLower(),
            "Garbage".ToLower(),
            "Gross".ToLower(),
            "Inferior".ToLower(),
            "Junky".ToLower(),
            "Abominable".ToLower(),
            "Amiss".ToLower(),
            "Careless".ToLower(),
            "Crappy".ToLower(),
            "Cruddy".ToLower(),
            "Defective".ToLower(),
            "Deficient".ToLower(),
            "Dissatisfactory".ToLower(),
            "Erroneous".ToLower(),
            "Fallacious".ToLower(),
            "Faulty".ToLower(),
            "Godawful".ToLower(),
            "Grody".ToLower(),
            "Grungy".ToLower(),
            "Icky".ToLower(),
            "Inadequate".ToLower(),
            "Incorrect".ToLower(),
            "Stinky".ToLower(),
            "Substandard".ToLower(),
            "Unsatisfactory".ToLower(),
            "Dangerous".ToLower(),
            "Unhealthy".ToLower(),
            "Damaging".ToLower(),
            "Deleterious".ToLower(),
            "Detrimental".ToLower(),
            "Hurtful".ToLower(),
            "Injurious".ToLower(),
            "Ruinous".ToLower(),
            "Evil".ToLower(),
            "Wrong".ToLower(),
            "Criminal".ToLower(),
            "Delinquent".ToLower(),
            "Mean".ToLower(),
            "Reprobate".ToLower(),
            "Corrupt".ToLower(),
            "Iniquitous".ToLower(),
            "Sinful".ToLower(),
            "Vicious".ToLower(),
            "Vile".ToLower(),
            "Villainous".ToLower(),
            "Wicked".ToLower(),
            "Wrong".ToLower(),
            "Disobedient".ToLower(),
            "Ill-behaved".ToLower(),
            "Misbehaving".ToLower(),
            "Naughty".ToLower(),
            "Unruly".ToLower(),
            "Rotten".ToLower(),
            "Sour".ToLower(),
            "Moldy".ToLower(),
            "Putrid".ToLower(),
            "Rancid".ToLower(),
            "Spoiled".ToLower(),
            "Disastrous".ToLower(),
            "Distressing".ToLower(),
            "Harsh".ToLower(),
            "Intense".ToLower(),
            "Painful".ToLower(),
            "Serious".ToLower(),
            "Terrible".ToLower(),
            "Grave".ToLower(),
            "Ill".ToLower(),
            "Ailing".ToLower(),
            "Diseased".ToLower(),
            "Pain".ToLower(),
            "Dead".ToLower(),
            "Unwell".ToLower(),
            "Downcast".ToLower(),
            "Low".ToLower(),
            "Regretful".ToLower(),
            "Upset".ToLower(),
            "Apologetic".ToLower(),
            "Conscience-stricken".ToLower(),
            "Contrite".ToLower(),
            "Crestfallen".ToLower(),
            "Dejected".ToLower(),
            "Depressed disconsolate".ToLower(),
            "Downhearted".ToLower(),
            "Guilty".ToLower(),
            "Remorseful".ToLower(),
            "Woebegone".ToLower(),
            "Grim".ToLower(),
            "Unfavorable".ToLower(),
            "Unfortunate".ToLower(),
            "Unpleasant".ToLower(),
            "Melancholy".ToLower(),
            "Adverse".ToLower(),
            "Somber".ToLower(),
            "Disagreeable".ToLower(),
            "Discouraged".ToLower(),
            "Discouraging".ToLower(),
            "Displeasing".ToLower(),
            "Distressed".ToLower(),
            "Gloomy".ToLower(),
            "Troubled".ToLower(),
            "Troubling".ToLower(),
            "Unhappy".ToLower(),
            "Dying".ToLower(),
            "Low".ToLower(),
            "evil",
            "disappointed",
            "destroy",
            "awful",
            "sinister",
            "sucks",
            "sucky",
            "gtfo",
            "wasted",
            "unyielding",
            "criticism",
            "threat",
            "threats",
            "worse",
            "worst",
            "killed",
            "massacred",
            "brutally",
            "brutal",
            "cruelties",
            "cruelest",
            "terror",
            "hell",
            "haters",
            "hater",
            "fear",
            "fearful",
            "fight",
            "fighting",
            "ass",
            "asshole",
            "hate",
            "discrimination",
            "discriminate",
            "crime",
            "hidden agenda",
            "alterior motives",
            "piss",
            "slaughter",
            "slaughtered",
            "pissed",
            ":(",
            ":'(",
            "difficult"

        };

        public static readonly string[] GoodWords =
        {
            ":-)",
            ":-P",
            ":P",
            ":)",
            "<3",
            "peace",
            "lol",
            "lmao",
            "lmfao",
            "recommend",
            "food",
            "funny",
            "bananas",
            "sistersbeforemisters",
            "delicious",
            "mouthwatering",
            "wedding",
            "engaged",
            "newlyweds",
            "champs",
            "champions",
            "swoon",
            "swooning",
            "friends",
            "bff",
            "married",
            "honeymoon",
            "congrats",
            "congratulations",
            "celebrate",
            "celebrating",
            "mrandmrs",
            "besties",
            "besty",
            "bffs",
            "bffl",
            "bffls",
            "ily",
            "ilysm",
            "kiss",
            "hubby",
            "sweetheart",
            "loved",
            "winners",
            "winning",
            "won",
            "cupcake",
            "icing",
            "sugar",
            "sugarpie",
            "sisters",
            "brothers",
            "solidarity",
            "bonding",
            "bond",
            "puppylove",
            "cutie",
            "cutiepie",
            "honey",
            "babe",
            "bae",
            "beautiful",
            "twinsies",
            "twinning",
            "smile",
            "radiating",
            "freedom",
            "love",
            "proud",
            "saved",
            "Good".ToLower(),
            "Acceptable".ToLower(),
            "Bad".ToLower(),
            "Excellent".ToLower(),
            "Exceptional".ToLower(),
            "Favorable".ToLower(),
            "Great".ToLower(),
            "Marvelous".ToLower(),
            "Positive".ToLower(),
            "Satisfactory".ToLower(),
            "Satisfying".ToLower(),
            "Superb".ToLower(),
            "Valuable".ToLower(),
            "Wonderful".ToLower(),
            "Ace".ToLower(),
            "Boss".ToLower(),
            "Capital".ToLower(),
            "Nice".ToLower(),
            "Pleasing".ToLower(),
            "Rad".ToLower(),
            "Super".ToLower(),
            "Superior".ToLower(),
            "Welcome".ToLower(),
            "Worthy".ToLower(),
            "Admirable".ToLower(),
            "Agreeable".ToLower(),
            "Commendable".ToLower(),
            "Congenial".ToLower(),
            "Deluxe".ToLower(),
            "First-class".ToLower(),
            "First-rate".ToLower(),
            "Gratifying".ToLower(),
            "Honorable".ToLower(),
            "Neat".ToLower(),
            "Precious".ToLower(),
            "Splendid".ToLower(),
            "Stupendous".ToLower(),
            "Honest".ToLower(),
            "Respectable".ToLower(),
            "Charitable".ToLower(),
            "Ethical".ToLower(),
            "Exemplary".ToLower(),
            "Incorrupt".ToLower(),
            "Praiseworthy".ToLower(),
            "Pure".ToLower(),
            "Uncorrupted".ToLower(),
            "Well-behaved".ToLower(),
            "Able".ToLower(),
            "Efficient".ToLower(),
            "Proper".ToLower(),
            "Reliable".ToLower(),
            "Suitable".ToLower(),
            "Talented".ToLower(),
            "Useful".ToLower(),
            "Adept".ToLower(),
            "Expert".ToLower(),
            "Accomplished".ToLower(),
            "Clever".ToLower(),
            "Dexterous".ToLower(),
            "Proficient".ToLower(),
            "Qualified".ToLower(),
            "Skillful".ToLower(),
            "Suited".ToLower(),
            "Thorough".ToLower(),
            "Trustworthy".ToLower(),
            "Advantageous".ToLower(),
            "Appropriate".ToLower(),
            "Beneficial".ToLower(),
            "Decent".ToLower(),
            "Desirable".ToLower(),
            "Favorable".ToLower(),
            "Healthy".ToLower(),
            "Helpful".ToLower(),
            "Profitable".ToLower(),
            "Satisfying".ToLower(),
            "Approving".ToLower(),
            "Brave".ToLower(),
            "Fit".ToLower(),
            "Fitting".ToLower(),
            "Apt".ToLower(),
            "Salutary".ToLower(),
            "Wholesome".ToLower(),
            "Flawless".ToLower(),
            "Perfect".ToLower(),
            "Stable".ToLower(),
            "Fresh".ToLower(),
            "Loyal".ToLower(),
            "Friendly".ToLower(),
            "Humanitarian".ToLower(),
            "Beneficent".ToLower(),
            "Benevolent".ToLower(),
            "Considerate".ToLower(),
            "Gracious".ToLower(),
            "Humane".ToLower(),
            "Kindhearted".ToLower(),
            "Merciful".ToLower(),
            "Obliging".ToLower(),
            "Philanthropic".ToLower(),
            "Legitimate".ToLower(),
            "Genuine".ToLower(),
            "Orderly".ToLower(),
            "Decorous".ToLower(),
            "Mannerly".ToLower(),
            "Polite".ToLower(),
            "Respectful".ToLower(),
            "Thoughtful".ToLower(),
            "Worthwhile".ToLower(),
            "Lucrative".ToLower(),
            "Blessing".ToLower(),
            "Favor".ToLower(),
            "Gain".ToLower(),
            "Godsend".ToLower(),
            "Prize".ToLower(),
            "Profit".ToLower(),
            "Treasure".ToLower(),
            "Fortunate".ToLower(),
            "Ideal".ToLower(),
            "Excellence".ToLower(),
            "Virtue".ToLower(),
            "love",
            "happy"
        };

        public static readonly string[] IrrelevantWords =
        {
            "a",
            "about",
            "about",
            "above",
            "above all",
            "accordingly",
            "across",
            "act",
            "actually",
            "additionally",
            "adjacent to",
            "after",
            "after all",
            "again",
            "against",
            "ahead",
            "aims",
            "air",
            "albeit",
            "all",
            "all in all",
            "all of a sudden",
            "all things considered",
            "alongside",
            "also",
            "although",
            "although this may be true",
            "altogether",
            "am",
            "amaze",
            "amazing",
            "american",
            "americans",
            "amid",
            "among",
            "an",
            "and",
            "another",
            "another key point",
            "any",
            "anybody",
            "anyone",
            "anything",
            "ap",
            "app",
            "apps",
            "are",
            "around",
            "art",
            "as",
            "as a matter of fact",
            "as a result",
            "as an illustration",
            "as can be seen",
            "as has been noted",
            "as long as",
            "as long as",
            "as much as",
            "as shown above",
            "as soon as",
            "as well as",
            "at",
            "at the",
            "at the present time",
            "at the same time",
            "at the same time",
            "at this instant",
            "attack",
            "awesome",
            "awesome",
            "awesome",
            "baby",
            "back",
            "bbc",
            "be",
            "be that as it may",
            "beautiful",
            "beautiful",
            "because of",
            "because the",
            "been",
            "before",
            "before",
            "behind",
            "being",
            "being",
            "being that",
            "below",
            "beneath",
            "benefits",
            "beside",
            "besides",
            "best",
            "better",
            "between",
            "beyond",
            "big",
            "bill",
            "billion",
            "billions",
            "black",
            "blow your mind",
            "blue",
            "both",
            "boy",
            "brown",
            "business",
            "but",
            "but",
            "but also",
            "buy",
            "by",
            "by",
            "by all means",
            "by and large",
            "by the same token",
            "by the time",
            "call",
            "calls",
            "can",
            "can't",
            "candidate",
            "cannot",
            "cant",
            "car",
            "care",
            "case",
            "caught",
            "cbs",
            "cells",
            "certainly",
            "chairman",
            "change",
            "change",
            "charged",
            "charges",
            "chief",
            "chiefly",
            "child",
            "city",
            "claims",
            "cnn",
            "come",
            "comparatively",
            "consequently",
            "conversely",
            "correspondingly",
            "could",
            "coupled with",
            "crisis",
            "cup",
            "data",
            "day",
            "day",
            "day",
            "day",
            "days",
            "de",
            "dead",
            "deal",
            "death",
            "Definitely",
            "despite",
            "did",
            "different from",
            "do",
            "do",
            "does",
            "dog",
            "dog",
            "down",
            "down",
            "due to",
            "during",
            "each",
            "each other",
            "eight",
            "eighteen",
            "eighty",
            "eighty-eight",
            "eighty-five",
            "eighty-four",
            "eighty-nine",
            "eighty-one",
            "eighty-seven",
            "eighty-six",
            "eighty-three",
            "eighty-two",
            "either",
            "eleven",
            "end",
            "episode",
            "equally",
            "equally important",
            "especially",
            "espn",
            "et",
            "even if",
            "even so",
            "even though",
            "eventually",
            "ever",
            "every",
            "everybody",
            "everyone",
            "everything",
            "explicitly",
            "expressly",
            "facebook",
            "facebook",
            "family",
            "few",
            "fifteen",
            "fifty",
            "fifty-eight",
            "fifty-five",
            "fifty-four",
            "fifty-nine",
            "fifty-one",
            "fifty-seven",
            "fifty-six",
            "fifty-three",
            "fifty-two",
            "fight",
            "final",
            "finally",
            "financial",
            "first",
            "first",
            "first",
            "first thing to remember",
            "five",
            "for",
            "for",
            "for example",
            "for fear that",
            "for instance",
            "for one thing",
            "for the first time",
            "for the most part",
            "for the purpose of",
            "for this reason",
            "for this reason",
            "former",
            "formerly",
            "forthwith",
            "forty",
            "forty-eight",
            "forty-five",
            "forty-four",
            "forty-nine",
            "forty-one",
            "forty-seven",
            "forty-six",
            "forty-three",
            "forty-two",
            "found",
            "four",
            "fourteen",
            "free",
            "frequently",
            "from",
            "from time to time",
            "full",
            "fund",
            "further",
            "further",
            "furthermore",
            "future",
            "game",
            "generally speaking",
            "get",
            "gets",
            "girl",
            "given that",
            "given these points",
            "go",
            "good",
            "google",
            "governor",
            "granted",
            "gray",
            "green",
            "guy",
            "had",
            "happened",
            "has",
            "has",
            "have",
            "have",
            "he",
            "heart",
            "heart",
            "hello",
            "help",
            "hence",
            "hence",
            "henceforth",
            "her",
            "here",
            "here and there",
            "here are the",
            "hers",
            "herself",
            "high",
            "him",
            "himself",
            "his",
            "his",
            "hit",
            "home",
            "house",
            "how",
            "how to",
            "how to make",
            "however",
            "huge",
            "hundreds",
            "i",
            "i've ever seen",
            "identically",
            "if",
            "if",
            "immediately",
            "important to realize",
            "in",
            "in",
            "in a",
            "in a moment",
            "in a word",
            "in addition",
            "in any event",
            "in brief",
            "in case",
            "in conclusion",
            "in contrast",
            "in detail",
            "in due time",
            "in effect",
            "in either case",
            "in essence",
            "in fact",
            "in fact",
            "in front of",
            "in general",
            "in like manner",
            "in order to",
            "in other words",
            "in particular",
            "in reality",
            "in short",
            "in spite of",
            "in summary",
            "in that case",
            "in the",
            "in the background",
            "in the center of",
            "in the distance",
            "in the event that",
            "in the final analysis",
            "in the first place",
            "in the first place",
            "in the foreground",
            "in the hope that",
            "in the light of",
            "in the long run",
            "in the meantime",
            "in the middle",
            "in the same fashion",
            "in the same way",
            "in the world",
            "in this case",
            "in time",
            "in view of",
            "inasmuch as",
            "including",
            "indeed",
            "instantly",
            "instead",
            "internet",
            "into",
            "is",
            "is the",
            "is what happens when",
            "it",
            "it is",
            "it looks like a",
            "it's",
            "it’s",
            "its",
            "itself",
            "just",
            "kids",
            "killed",
            "know",
            "know",
            "last",
            "later",
            "latest",
            "law",
            "lest",
            "life",
            "like",
            "like a normal",
            "likewise",
            "little",
            "little",
            "live",
            "ll",
            "long",
            "look",
            "look",
            "look like a normal",
            "looks like a",
            "love",
            "love",
            "made",
            "made",
            "make",
            "make",
            "make you",
            "makes",
            "man",
            "man",
            "many",
            "markedly",
            "market",
            "may",
            "me",
            "me",
            "meanwhile",
            "media",
            "meet",
            "men",
            "might look like a",
            "million",
            "millions",
            "mind",
            "mine",
            "mobile",
            "money",
            "more",
            "more",
            "moreover",
            "most",
            "most",
            "most compelling evidence",
            "much",
            "music",
            "must",
            "must be remembered",
            "my",
            "myself",
            "namely",
            "near",
            "nearby",
            "need",
            "neither",
            "never",
            "never",
            "nevertheless",
            "new",
            "new",
            "new",
            "news",
            "next",
            "next",
            "night",
            "nine",
            "nineteen",
            "ninety",
            "ninety-eight",
            "ninety-five",
            "ninety-four",
            "ninety-nine",
            "ninety-one",
            "ninety-seven",
            "ninety-six",
            "ninety-three",
            "ninety-two",
            "no",
            "no one",
            "nobody",
            "none",
            "nonetheless",
            "not",
            "not",
            "not only",
            "not to mention",
            "notably",
            "nothing",
            "notwithstanding",
            "now",
            "now",
            "now",
            "now",
            "now that",
            "npr",
            "Obviously",
            "occasionally",
            "of",
            "of",
            "of course",
            "of course",
            "of the",
            "off",
            "office",
            "old",
            "old",
            "old",
            "on",
            "on",
            "on balance",
            "on condition",
            "on the",
            "on the condition",
            "on the contrary",
            "on the negative side",
            "on the other hand",
            "on the positive side",
            "on the whole",
            "on this side",
            "once",
            "one",
            "one",
            "one",
            "one",
            "one another",
            "one hundred",
            "online",
            "only",
            "open",
            "opposite to ",
            "or",
            "orange",
            "ordinarily",
            "other",
            "others",
            "otherwise",
            "our",
            "ours",
            "ourselves",
            "out",
            "out",
            "over",
            "overall",
            "owing to",
            "particularly",
            "people",
            "people",
            "photos",
            "photos",
            "pictures",
            "pink",
            "plans",
            "pm",
            "point often overlooked",
            "politics",
            "presently",
            "prior to",
            "provided that",
            "purple",
            "quickly",
            "raise",
            "rather",
            "re",
            "reach",
            "real",
            "really",
            "reasons",
            "red",
            "regardless",
            "reveals",
            "review",
            "right",
            "risk",
            "round",
            "rules",
            "ruling",
            "run",
            "said",
            "say",
            "saying",
            "says",
            "school",
            "second",
            "second",
            "see",
            "see",
            "seeing that",
            "seeks",
            "seen",
            "sees",
            "set",
            "seven",
            "seventeen",
            "seventy",
            "seventy-eight",
            "seventy-five",
            "seventy-four",
            "seventy-nine",
            "seventy-one",
            "seventy-seven",
            "seventy-six",
            "seventy-three",
            "seventy-two",
            "several",
            "she",
            "she",
            "she",
            "shortly",
            "shot",
            "should",
            "show",
            "shows",
            "significantly",
            "signs",
            "similarly",
            "since",
            "since",
            "since",
            "six",
            "sixteen",
            "sixty",
            "sixty-eight",
            "sixty-five",
            "sixty-four",
            "sixty-nine",
            "sixty-one",
            "sixty-seven",
            "sixty-six",
            "sixty-three",
            "sixty-two",
            "small",
            "so",
            "so as to",
            "so long as",
            "so that",
            "social",
            "some",
            "somebody",
            "someone",
            "something",
            "something",
            "son",
            "sooner or later",
            "specifically",
            "sports",
            "star",
            "state",
            "still",
            "stocks",
            "stop",
            "straightaway",
            "study",
            "such as",
            "suddenly",
            "summer",
            "supreme",
            "surely",
            "surprisingly",
            "survey",
            "take",
            "team",
            "tech",
            "teen",
            "ten",
            "tens",
            "th",
            "than",
            "that",
            "that",
            "that is to say",
            "that will",
            "that will make",
            "that will make you",
            "the",
            "the",
            "the best",
            "the definitive ranking of",
            "the most",
            "the reason why is",
            "their",
            "their",
            "theirs",
            "them",
            "themselves",
            "then",
            "then",
            "then",
            "then",
            "then again",
            "there",
            "there",
            "therefore",
            "thereupon",
            "these",
            "these",
            "they",
            "they",
            "thing",
            "thing",
            "thing i've ever seen",
            "things",
            "things",
            "think",
            "third",
            "thirteen",
            "thirty",
            "thirty-eight",
            "thirty-five",
            "thirty-four",
            "thirty-nine",
            "thirty-one",
            "thirty-seven",
            "thirty-six",
            "thirty-three",
            "thirty-two",
            "this",
            "this guy",
            "this is",
            "this is the",
            "this is what",
            "this is what happens",
            "those",
            "though",
            "thousands",
            "threat",
            "three",
            "thus",
            "ties",
            "til you see",
            "til you see what",
            "till",
            "time",
            "title",
            "to",
            "to",
            "to be",
            "to be sure",
            "to begin with",
            "to clarify",
            "to demonstrate",
            "to emphasize",
            "to enumerate",
            "to explain",
            "to point out",
            "to put it another way",
            "to put it differently",
            "to repeat",
            "to say nothing of",
            "to sum up",
            "to summarize",
            "to the",
            "to the end that",
            "to the left",
            "to the right",
            "todo",
            "together with",
            "too",
            "top",
            "tour",
            "trade",
            "trillions",
            "truly",
            "tv",
            "twelve",
            "twenty",
            "twenty-eight",
            "twenty-five",
            "twenty-four",
            "twenty-nine",
            "twenty-one",
            "twenty-seven",
            "twenty-six",
            "twenty-three",
            "twenty-two",
            "two",
            "ultimately",
            "under",
            "under those circumstances",
            "uniquely",
            "unless",
            "unlike",
            "until",
            "until now",
            "up",
            "up to the present time",
            "update",
            "us",
            "use",
            "usually",
            "valentine’s",
            "video",
            "video",
            "vote",
            "wait til you",
            "wait til you see",
            "want",
            "was",
            "was",
            "watch",
            "way",
            "way",
            "ways",
            "we",
            "week",
            "were",
            "what",
            "what happened",
            "what happened to",
            "what happened to this",
            "what happens when",
            "what he did",
            "what he found is",
            "what this",
            "what this guy",
            "what's",
            "whatever",
            "whats",
            "when",
            "when",
            "when",
            "when you",
            "when you see",
            "whenever",
            "whenever",
            "whenever",
            "where",
            "whereas",
            "wherever",
            "which",
            "whichever",
            "while",
            "white",
            "who",
            "whoever",
            "whom",
            "whomever",
            "whose",
            "why",
            "will",
            "will blow your mind",
            "will have",
            "will make you",
            "win",
            "wins",
            "with",
            "with attention to",
            "with this in mind",
            "with this in mind",
            "with this intention",
            "without",
            "without delay",
            "woman",
            "women",
            "womens",
            "women's",
            "wont",
            "work",
            "world",
            "worlds",
            "would",
            "year",
            "year",
            "years",
            "yellow",
            "yet",
            "york",
            "you",
            "you need to",
            "you need to know",
            "you see",
            "you see what",
            "you’ll",
            "your",
            "your",
            "yours",
            "yourself",
            "yourselves",
            "youtube",
            "zero",
            "face",
            "war",
            "robot",
            "plane",
            "cost",
            "powered",
            "miss",
            "court",
            "own",
            "united",
            "article",
            "bank",
            "south",
            "sex",
            "stock",
            "making",
            "report",
            "start",
            "global",
            "give",
            "leaders",
            "uk",
            "marketing",
            "don",
            "scientists",
            "content",
            "using",
            "football",
            "test",
            "tests"
        };
    }
}